### ISSUE TITLE
Duplicate ARM API hostname in generated URL

### ISSUE THREAD

**Issue by shellguard** [asheniam/armclient#7]
Hello,

Thanks for an amazing tool. When I run the binary I face the following issue:
FATA[0002] Error sending HTTP request: Get https://management.azure.comhttps//management.azure.com/subscriptions/...

It seems that targetUrl in azureclient.go lists it twice

Any ideas?

Thank you!

**Comment by asheniam** [comment]
When you use armclient get <url>, you should set <url>=/subscriptions/... without the hostname.

**Comment by asheniam** [comment]
Hm, I haven't run into that error before.  Can you rerun with the debug flag and share the output?  Please scrub the subscriptionID from the logs.

**Comment by stlandry** [comment]
I'm getting the same issue.  Here's the output with the debug flag

[root@rhelmon armclient]# ./armclient --config.file="/root/armclient/sample-azure.yml" --debug grafana --title=TITLE --datasource="Azure Pathfinder PROD" --resourcetype=Microsoft.Compute/virtualMachines                                   DEBU[0000] Getting token from https://login.microsoftonline.com/6397df10-4595-4047-9c4f-03311282152b/oauth2/token
INFO[0000] Running GET /subscriptions/###################/resources?api-version=2017-08-01
DEBU[0000] Executing GET https://management.azure.com/subscriptions/###################//resources?api-version=2017-08-01
DEBU[0000] Status code: 200
INFO[0000] Running GET https://management.azure.com/subscriptions/###################//resources?api-version=2017-08-01&%24skiptoken=eyJuZXh0UGFydGl0aW9uS2V5IjoiMSE4IU1VUTRNREktIiwibmV4dFJvd0tleSI6IjEhMTc2IVJUUTFNakkyUXpWR09VVTVORGszT1Rrd01UWTVOa0pCTWpkQ01UVTJRMEpmUjFKTUxWSkhPalZHUmsxVU9qVkdRVXhNT2pWR1ZrVlNWRWxEUVV4VExVMUpRMUpQVTA5R1ZEb3lSVU5QVFZCVlZFVTZNa1pXU1ZKVVZVRk1UVUZEU0VsT1JWTTZNa1pHVFZRNk1rUkJSRXhCVFVFd01TMURRVTVCUkVGRFJVNVVVa0ZNIn0%3d/
DEBU[0000] Executing GET https://management.azure.comhttps://management.azure.com/subscriptions/###################//resources?api-version=2017-08-01&%24skiptoken=eyJuZXh0UGFydGl0aW9uS2V5IjoiMSE4IU1VUTRNREktIiwibmV4dFJvd0tleSI6IjEhMTc2IVJUUTFNakkyUXpWR09VVTVORGszT1Rrd01UWTVOa0pCTWpkQ01UVTJRMEpmUjFKTUxWSkhPalZHUmsxVU9qVkdRVXhNT2pWR1ZrVlNWRWxEUVV4VExVMUpRMUpQVTA5R1ZEb3lSVU5QVFZCVlZFVTZNa1pXU1ZKVVZVRk1UVUZEU0VsT1JWTTZNa1pHVFZRNk1rUkJSRXhCVFVFd01TMURRVTVCUkVGRFJVNVVVa0ZNIn0%3d/
FATA[0000] Error sending HTTP request: Get https://management.azure.comhttps//management.azure.com/subscriptions/###################//resources?api-version=2017-08-01&%24skiptoken=eyJuZXh0UGFydGl0aW9uS2V5IjoiMSE4IU1VUTRNREktIiwibmV4dFJvd0tleSI6IjEhMTc2IVJUUTFNakkyUXpWR09VVTVORGszT1Rrd01UWTVOa0pCTWpkQ01UVTJRMEpmUjFKTUxWSkhPalZHUmsxVU9qVkdRVXhNT2pWR1ZrVlNWRWxEUVV4VExVMUpRMUpQVTA5R1ZEb3lSVU5QVFZCVlZFVTZNa1pXU1ZKVVZVRk1UVUZEU0VsT1JWTTZNa1pHVFZRNk1rUkJSRXhCVFVFd01TMURRVTVCUkVGRFJVNVVVa0ZNIn0%3d/: dial tcp: lookup management.azure.comhttps on 10.54.10.6:53: no such host

**Comment by asheniam** [comment]
This looks like a bug in the armclient tool when following continuation tokens.  As a workaround temporarily, can you try to set the maxcontinuation flag to 0 when you run the grafana command?  

Run './armclient help grafana' to see the parameter.

**Comment by asheniam** [comment]
I added a fix for this continuation token issue.  Please grab the latest source, re-build, and try running the command again.

**Comment by stlandry** [comment]
Hi asheniam,

I grabbed the latest source and re-built

If I add the --maxcontinuation=0 flag it seems to work

 ./armclient grafana --maxcontinuation=0 --title=TITLE --datasource="Azure Pathfinder PROD" --resourcetype=microsoft-compute-virtualmachines
INFO[0000] Running GET /subscriptions/#####################/resources?api-version=2017-08-01
Created dashboard_title_microsoft-compute-virtualmachines_overview_allregions.json

without it, I'm getting a InvalidContinuationToken error

 ./armclient grafana --debug --title=TITLE --datasource="Azure Pathfinder PROD" --resourcetype=microsoft-compute-virtualmachines
DEBU[0000] Getting token from https://login.microsoftonline.com/6397df10-4595-4047-9c4f-03311282152b/oauth2/token
INFO[0000] Running GET /subscriptions/###################/resources?api-version=2017-08-01
DEBU[0000] Executing GET https://management.azure.com/subscriptions/###################/resources?api-version=2017-08-01
DEBU[0000] Status code: 200
INFO[0000] Running GET https://management.azure.com/subscriptions/#######################/resources?api-version=2017-08-01&%24skiptoken=eyJuZXh0UGFydGl0aW9uS2V5IjoiMSE4IU1VUTRNREktIiwibmV4dFJvd0tleSI6IjEhMTc2IVJUUTFNakkyUXpWR09VVTVORGszT1Rrd01UWTVOa0pCTWpkQ01UVTJRMEpmUjFKTUxWSkhPalZHUmsxVU9qVkdRVXhNT2pWR1ZrVlNWRWxEUVV4VExVMUpRMUpQVTA5R1ZEb3lSVU5QVFZCVlZFVTZNa1pXU1ZKVVZVRk1UVUZEU0VsT1JWTTZNa1pHVFZRNk1rUkJSRWhRVTFNd01TMURRVTVCUkVGRFJVNVVVa0ZNIn0%3d/
DEBU[0000] Executing GET https://management.azure.com/subscriptions/#################/resources?api-version=2017-08-01&%24skiptoken=eyJuZXh0UGFydGl0aW9uS2V5IjoiMSE4IU1VUTRNREktIiwibmV4dFJvd0tleSI6IjEhMTc2IVJUUTFNakkyUXpWR09VVTVORGszT1Rrd01UWTVOa0pCTWpkQ01UVTJRMEpmUjFKTUxWSkhPalZHUmsxVU9qVkdRVXhNT2pWR1ZrVlNWRWxEUVV4VExVMUpRMUpQVTA5R1ZEb3lSVU5QVFZCVlZFVTZNa1pXU1ZKVVZVRk1UVUZEU0VsT1JWTTZNa1pHVFZRNk1rUkJSRWhRVTFNd01TMURRVTVCUkVGRFJVNVVVa0ZNIn0%3d/
DEBU[0000] Status code: 400
ERRO[0000] Error sending HTTP request with status code: 400
{
  "error": {
    "code": "InvalidContinuationToken",
    "message": "Invalid continuation token in the request uri. Continuation token - 'eyJuZXh0UGFydGl0aW9uS2V5IjoiMSE4IU1VUTRNREktIiwibmV4dFJvd0tleSI6IjEhMTc2IVJUUTFNakkyUXpWR09VVTVORGszT1Rrd01UWTVOa0pCTWpkQ01UVTJRMEpmUjFKTUxWSkhPalZHUmsxVU9qVkdRVXhNT2pWR1ZrVlNWRWxEUVV4VExVMUpRMUpQVTA5R1ZEb3lSVU5QVFZCVlZFVTZNa1pXU1ZKVVZVRk1UVUZEU0VsT1JWTTZNa1pHVFZRNk1rUkJSRWhRVTFNd01TMURRVTVCUkVGRFJVNVVVa0ZNIn0=/'."
  }
}
FATA[0000] Error unmarshalling ARM reource response body: unexpected end of JSON input

**Comment by epleterte** [comment]
I believe I am getting the same error with the latest version, running the `grafana` command.
If I set `maxcontinuation` to `0`, it works. 
My previous command with `50` gives the `lookup management.azure.comhttps` `no such host` error.
