### ISSUE TITLE
How do I compile this?

### ISSUE THREAD

**Issue by wayno4** [asheniam/armclient#9]
Sorry for the basic question, but how do I compile the armclient?  I'm looking to test out Grafana in Azure and would love to use your Dahsboards as a starting point

**Comment by asheniam** [comment]
1) Download Go tool chain - go build -o <executable name> .
2) Download the source code and go into the directory
3) go build -o <executable name> .

**Comment by wayno4** [comment]
Seems I'm doing something wrong
Downloaded Go for Windows from https://golang.org/dl/ 
Downloaded armclient sourcecode and ran "go build -o . 
Results in the below errors
armcontracts.go:8:2: cannot find package "github.com/ahmetb/go-linq" in any of:
        C:\Go\src\github.com\ahmetb\go-linq (from $GOROOT)
        C:\Users\wayno\go\src\github.com\ahmetb\go-linq (from $GOPATH)
armcontracts.go:9:2: cannot find package "github.com/sirupsen/logrus" in any of:
        C:\Go\src\github.com\sirupsen\logrus (from $GOROOT)
        C:\Users\wayno\go\src\github.com\sirupsen\logrus (from $GOPATH)
main.go:7:2: cannot find package "gopkg.in/alecthomas/kingpin.v2" in any of:
        C:\Go\src\gopkg.in\alecthomas\kingpin.v2 (from $GOROOT)
        C:\Users\wayno\go\src\gopkg.in\alecthomas\kingpin.v2 (from $GOPATH)
config.go:8:2: cannot find package "gopkg.in/yaml.v2" in any of:
        C:\Go\src\gopkg.in\yaml.v2 (from $GOROOT)
        C:\Users\wayno\go\src\gopkg.in\yaml.v2 (from $GOPATH)

**Comment by asheniam** [comment]
You need to use go get to download the dependencies
